"""
Chapter 4 Portfolio Turnover and Concentration Analysis

This script builds Table 4.3, Figure 4.3, and Figure 4.4 for the master's thesis:

Portfolio Stability Under Stressed Market Conditions:
A Comparative Analysis of Mean-Variance, CVaR, and Robust Portfolio Optimization

It reads the portfolio weight files produced by chapter4_backtest.py and calculates:
- Average portfolio turnover
- Maximum portfolio turnover
- Average portfolio concentration using the Herfindahl-Hirschman Index (HHI)
- Maximum portfolio concentration using the Herfindahl-Hirschman Index (HHI)

Expected inputs:
    chapter4_outputs/weights_constrained_mean_variance.csv
    chapter4_outputs/weights_cvar_optimization.csv
    chapter4_outputs/weights_robust_mean_variance.csv

Generated outputs:
    chapter4_outputs/table_4_3_raw.csv
    chapter4_outputs/table_4_3_formatted.csv
    chapter4_outputs/figure_4_3_turnover.png
    chapter4_outputs/figure_4_4_concentration.png
"""

from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# SETTINGS
# ============================================================

OUTPUT_DIR = Path("chapter4_outputs")

WEIGHT_FILES = {
    "Constrained Mean-Variance": OUTPUT_DIR / "weights_constrained_mean_variance.csv",
    "CVaR Optimization": OUTPUT_DIR / "weights_cvar_optimization.csv",
    "Robust Mean-Variance": OUTPUT_DIR / "weights_robust_mean_variance.csv",
}


# ============================================================
# LOAD PORTFOLIO WEIGHTS
# ============================================================

def load_weight_files() -> dict[str, pd.DataFrame]:
    """
    Load the portfolio weight files generated by chapter4_backtest.py.

    Returns
    -------
    dict[str, pd.DataFrame]
        Dictionary containing portfolio weights for each optimization method.
    """
    weights_dict = {}

    for method, file_path in WEIGHT_FILES.items():
        if not file_path.exists():
            raise FileNotFoundError(
                f"Could not find {file_path}. "
                "Please run src/chapter4_backtest.py first to generate the weight files."
            )

        weights_dict[method] = pd.read_csv(
            file_path,
            index_col=0,
            parse_dates=True,
        )

    return weights_dict


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def turnover_series(weights_df: pd.DataFrame) -> pd.Series:
    """
    Calculate portfolio turnover over time.

    Turnover is measured as the sum of absolute month-to-month changes
    in portfolio weights.

    Parameters
    ----------
    weights_df : pd.DataFrame
        Portfolio weights over time.

    Returns
    -------
    pd.Series
        Portfolio turnover time series.
    """
    return weights_df.diff().abs().sum(axis=1)


def concentration_series(weights_df: pd.DataFrame) -> pd.Series:
    """
    Calculate portfolio concentration over time using HHI.

    The Herfindahl-Hirschman Index is calculated as the sum of squared
    portfolio weights. A higher value indicates a more concentrated portfolio.

    Parameters
    ----------
    weights_df : pd.DataFrame
        Portfolio weights over time.

    Returns
    -------
    pd.Series
        Portfolio concentration time series.
    """
    return (weights_df ** 2).sum(axis=1)


# ============================================================
# TABLE 4.3
# ============================================================

def build_table_4_3(weights_dict: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """
    Build the raw turnover and concentration statistics table.

    Parameters
    ----------
    weights_dict : dict[str, pd.DataFrame]
        Portfolio weights for each optimization method.

    Returns
    -------
    pd.DataFrame
        Raw Table 4.3 values.
    """
    rows = []

    for method, weights_df in weights_dict.items():
        turnover = turnover_series(weights_df).dropna()
        concentration = concentration_series(weights_df).dropna()

        rows.append({
            "Method": method,
            "Average Turnover": turnover.mean(),
            "Maximum Turnover": turnover.max(),
            "Average Concentration (HHI)": concentration.mean(),
            "Maximum Concentration (HHI)": concentration.max(),
        })

    return pd.DataFrame(rows)


def format_table_4_3(table: pd.DataFrame) -> pd.DataFrame:
    """
    Format Table 4.3 for thesis presentation.

    Parameters
    ----------
    table : pd.DataFrame
        Raw Table 4.3 values.

    Returns
    -------
    pd.DataFrame
        Formatted Table 4.3 values.
    """
    out = table.copy()

    out["Average Turnover"] = (out["Average Turnover"] * 100).map(lambda x: f"{x:.2f}%")
    out["Maximum Turnover"] = (out["Maximum Turnover"] * 100).map(lambda x: f"{x:.2f}%")
    out["Average Concentration (HHI)"] = out["Average Concentration (HHI)"].map(lambda x: f"{x:.3f}")
    out["Maximum Concentration (HHI)"] = out["Maximum Concentration (HHI)"].map(lambda x: f"{x:.3f}")

    return out


# ============================================================
# FIGURE 4.3 AND FIGURE 4.4
# ============================================================

def plot_figure_4_3(weights_dict: dict[str, pd.DataFrame], output_path: Path) -> None:
    """
    Plot portfolio turnover over time for all portfolio methods.

    Parameters
    ----------
    weights_dict : dict[str, pd.DataFrame]
        Portfolio weights for each optimization method.
    output_path : Path
        File path for saving the figure.
    """
    plt.figure(figsize=(10, 6))

    for method, weights_df in weights_dict.items():
        turnover = turnover_series(weights_df).dropna()
        plt.plot(turnover.index, turnover * 100, label=method)

    plt.title("Figure 4.3. Portfolio Turnover Over Time")
    plt.xlabel("Date")
    plt.ylabel("Turnover (%)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()


def plot_figure_4_4(weights_dict: dict[str, pd.DataFrame], output_path: Path) -> None:
    """
    Plot portfolio concentration over time for all portfolio methods.

    Parameters
    ----------
    weights_dict : dict[str, pd.DataFrame]
        Portfolio weights for each optimization method.
    output_path : Path
        File path for saving the figure.
    """
    plt.figure(figsize=(10, 6))

    for method, weights_df in weights_dict.items():
        concentration = concentration_series(weights_df).dropna()
        plt.plot(concentration.index, concentration, label=method)

    plt.title("Figure 4.4. Portfolio Concentration Over Time")
    plt.xlabel("Date")
    plt.ylabel("HHI Concentration")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()


# ============================================================
# SAVE OUTPUTS
# ============================================================

def save_outputs(weights_dict: dict[str, pd.DataFrame], table_4_3: pd.DataFrame) -> None:
    """
    Save Table 4.3, Figure 4.3, and Figure 4.4 outputs.

    Parameters
    ----------
    weights_dict : dict[str, pd.DataFrame]
        Portfolio weights for each optimization method.
    table_4_3 : pd.DataFrame
        Raw Table 4.3 values.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    table_4_3.to_csv(OUTPUT_DIR / "table_4_3_raw.csv", index=False)
    format_table_4_3(table_4_3).to_csv(OUTPUT_DIR / "table_4_3_formatted.csv", index=False)

    plot_figure_4_3(
        weights_dict=weights_dict,
        output_path=OUTPUT_DIR / "figure_4_3_turnover.png",
    )

    plot_figure_4_4(
        weights_dict=weights_dict,
        output_path=OUTPUT_DIR / "figure_4_4_concentration.png",
    )


# ============================================================
# RUN EVERYTHING
# ============================================================

def main() -> None:
    print("Loading portfolio weights...")
    weights_dict = load_weight_files()

    print("Building Table 4.3...")
    table_4_3 = build_table_4_3(weights_dict)

    print("\nTable 4.3 (raw):")
    print(table_4_3)

    print("\nTable 4.3 (formatted):")
    print(format_table_4_3(table_4_3))

    save_outputs(weights_dict, table_4_3)

    print(f"\nSaved outputs to: {OUTPUT_DIR.resolve()}")


if __name__ == "__main__":
    main()
