# -*- coding: utf-8 -*-
"""Portfolio_weights_figures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MY_pTVbmDv6HxS8RpVZp3KbfjIG64UQQ
"""

import zipfile
import re
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize, linprog


# =====================================================
# SETTINGS
# =====================================================

DATA_ZIP = Path("49_Industry_Portfolios_CSV.zip")

OUTPUT_DIR = Path("chapter4_outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

ROLLING_WINDOW = 60
START_OOS = "1990-01-01"
END_OOS = "2026-03-01"

LOWER_BOUND = 0.00
UPPER_BOUND = 0.10

TARGET_MULTIPLIER = 0.95
CVAR_ALPHA = 0.95
ROBUST_LAMBDA = 0.5

SELECTED_DATE = "2020-03-01"


# =====================================================
# LOAD KENNETH FRENCH 49 INDUSTRY DATA
# =====================================================

def load_kf_49_monthly(zip_path):
    """
    Loads monthly value-weighted returns from the Kenneth French
    49 Industry Portfolios zip file.

    Important:
    This version keeps all 49 industry columns.
    It does not drop columns with missing values.
    """
    with zipfile.ZipFile(zip_path, "r") as z:
        csv_name = z.namelist()[0]
        raw = z.read(csv_name).decode("latin1")

    lines = raw.splitlines()

    start = None
    for i, line in enumerate(lines):
        if "Average Value Weighted Returns -- Monthly" in line:
            start = i
            break

    if start is None:
        raise ValueError("Could not find monthly value-weighted returns section.")

    header = lines[start + 1].split(",")
    rows = []

    for line in lines[start + 2:]:
        if not line.strip():
            break

        parts = line.split(",")

        if len(parts) < 2:
            break

        date_value = parts[0].strip()

        if re.fullmatch(r"\d{6}", date_value):
            rows.append(parts)
        else:
            break

    df = pd.DataFrame(rows, columns=header)
    df.rename(columns={df.columns[0]: "Date"}, inplace=True)

    df["Date"] = pd.to_datetime(df["Date"], format="%Y%m")

    for col in df.columns[1:]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.set_index("Date")

    # Replace Kenneth French missing-value codes with NaN
    df = df.replace([-99.99, -999, -999.0], np.nan)

    # Do NOT drop columns.
    # The thesis uses the 49 Industry Portfolios, so all columns should remain.
    df = df / 100.0

    return df


returns = load_kf_49_monthly(DATA_ZIP)

print("Return data loaded:")
print(returns.shape)
print("Date range:", returns.index.min(), "to", returns.index.max())

if returns.shape[1] != 49:
    print("WARNING: The loaded data does not contain 49 portfolios.")
    print("Number of columns loaded:", returns.shape[1])
    print("Columns:")
    print(list(returns.columns))
else:
    print("Correct: 49 industry portfolios loaded.")


# =====================================================
# OPTIMIZATION FUNCTIONS
# =====================================================

def target_return(mu_hat):
    return TARGET_MULTIPLIER * mu_hat.mean()


def solve_mean_variance(mu_hat, cov_hat, target):
    """
    Constrained mean-variance optimization.

    Objective:
        minimize w' Sigma w

    Constraints:
        sum(w) = 1
        w' mu >= target
        0 <= w_i <= 0.10
    """
    n = len(mu_hat)

    x0 = np.repeat(1 / n, n)

    bounds = [(LOWER_BOUND, UPPER_BOUND) for _ in range(n)]

    constraints = [
        {"type": "eq", "fun": lambda w: np.sum(w) - 1},
        {"type": "ineq", "fun": lambda w: np.dot(w, mu_hat) - target},
    ]

    cov_stable = cov_hat + 1e-8 * np.eye(n)

    result = minimize(
        fun=lambda w: np.dot(w, cov_stable @ w),
        x0=x0,
        method="SLSQP",
        bounds=bounds,
        constraints=constraints,
        options={
            "ftol": 1e-9,
            "maxiter": 500,
            "disp": False
        }
    )

    if not result.success:
        raise RuntimeError(result.message)

    return result.x


def solve_robust_mean_variance(mu_hat, cov_hat, hist_returns, target):
    """
    Robust mean-variance optimization.

    Robust expected return:
        mu_robust = mu_hat - lambda * SE(mu_hat)
    """
    se_mu = hist_returns.std(ddof=1).values / np.sqrt(len(hist_returns))
    mu_robust = mu_hat - ROBUST_LAMBDA * se_mu

    return solve_mean_variance(mu_robust, cov_hat, target)


def solve_cvar(hist_returns, mu_hat, target):
    """
    CVaR optimization solved by linear programming.

    Variables:
        w_1, ..., w_n, zeta, u_1, ..., u_T

    Objective:
        minimize zeta + 1 / ((1-alpha)T) * sum(u_t)

    Loss definition:
        L_t(w) = -r_t'w
    """
    R = hist_returns.values
    T, n = R.shape

    c = np.zeros(n + 1 + T)

    # zeta coefficient
    c[n] = 1.0

    # auxiliary variables coefficient
    c[n + 1:] = 1.0 / ((1.0 - CVAR_ALPHA) * T)

    # Equality constraint: sum weights = 1
    A_eq = np.zeros((1, n + 1 + T))
    A_eq[0, :n] = 1.0
    b_eq = np.array([1.0])

    A_ub = []
    b_ub = []

    # Target return:
    # w' mu >= target  ->  -w' mu <= -target
    row = np.zeros(n + 1 + T)
    row[:n] = -mu_hat
    A_ub.append(row)
    b_ub.append(-target)

    # CVaR auxiliary constraints:
    # u_t >= loss_t - zeta
    # loss_t = -R_t w
    # -R_t w - zeta - u_t <= 0
    for t in range(T):
        row = np.zeros(n + 1 + T)
        row[:n] = -R[t, :]
        row[n] = -1.0
        row[n + 1 + t] = -1.0
        A_ub.append(row)
        b_ub.append(0.0)

    A_ub = np.array(A_ub)
    b_ub = np.array(b_ub)

    bounds = []

    # Portfolio weight bounds
    for _ in range(n):
        bounds.append((LOWER_BOUND, UPPER_BOUND))

    # zeta is unrestricted
    bounds.append((None, None))

    # u_t auxiliary variables are non-negative
    for _ in range(T):
        bounds.append((0, None))

    result = linprog(
        c=c,
        A_ub=A_ub,
        b_ub=b_ub,
        A_eq=A_eq,
        b_eq=b_eq,
        bounds=bounds,
        method="highs"
    )

    if not result.success:
        raise RuntimeError(result.message)

    return result.x[:n]


# =====================================================
# RUN ROLLING BACKTEST TO GENERATE WEIGHTS
# =====================================================

dates = returns.loc[START_OOS:END_OOS].index

weights_mv = []
weights_cvar = []
weights_robust = []
used_dates = []
failed_dates = []

for date in dates:
    date_position = returns.index.get_loc(date)

    if date_position < ROLLING_WINDOW:
        continue

    hist = returns.iloc[date_position - ROLLING_WINDOW:date_position]

    # Skip only if the current 60-month window has missing values.
    # Do not delete whole industry columns from the full dataset.
    if hist.isna().any().any():
        failed_dates.append((date, "Missing values in 60-month estimation window"))
        continue

    mu_hat = hist.mean().values
    cov_hat = hist.cov().values
    target = target_return(mu_hat)

    try:
        w_mv = solve_mean_variance(mu_hat, cov_hat, target)
        w_cvar = solve_cvar(hist, mu_hat, target)
        w_robust = solve_robust_mean_variance(mu_hat, cov_hat, hist, target)

        weights_mv.append(w_mv)
        weights_cvar.append(w_cvar)
        weights_robust.append(w_robust)
        used_dates.append(date)

    except Exception as e:
        failed_dates.append((date, str(e)))


weights_mv = pd.DataFrame(weights_mv, index=used_dates, columns=returns.columns)
weights_cvar = pd.DataFrame(weights_cvar, index=used_dates, columns=returns.columns)
weights_robust = pd.DataFrame(weights_robust, index=used_dates, columns=returns.columns)

print("Successful months:", len(used_dates))
print("Failed months:", len(failed_dates))

if failed_dates:
    print("First few failed dates:")
    print(failed_dates[:10])


# Save weight files
weights_mv.to_csv(OUTPUT_DIR / "weights_constrained_mean_variance.csv")
weights_cvar.to_csv(OUTPUT_DIR / "weights_cvar_optimization.csv")
weights_robust.to_csv(OUTPUT_DIR / "weights_robust_mean_variance.csv")

print("Weight files saved.")


# =====================================================
# SELECT DATE FOR ILLUSTRATIVE FIGURES
# =====================================================

selected_date = pd.Timestamp(SELECTED_DATE)

common_dates = (
    weights_mv.index
    .intersection(weights_cvar.index)
    .intersection(weights_robust.index)
)

if len(common_dates) == 0:
    raise ValueError("No common successful dates across the three methods.")

if selected_date not in common_dates:
    closest_date = common_dates[np.argmin(np.abs(common_dates - selected_date))]
    print(f"Selected date {selected_date.date()} not found.")
    print(f"Using closest available date: {closest_date.date()}")
    selected_date = closest_date
else:
    print(f"Using selected date: {selected_date.date()}")


# =====================================================
# FIGURE 1: ACTUAL PORTFOLIO WEIGHTS
# =====================================================

weights_selected = pd.DataFrame({
    "Constrained Mean-Variance": weights_mv.loc[selected_date],
    "CVaR Optimization": weights_cvar.loc[selected_date],
    "Robust Mean-Variance": weights_robust.loc[selected_date]
})

weights_selected = weights_selected.sort_values(
    by="Constrained Mean-Variance",
    ascending=False
)

plt.figure(figsize=(18, 7))

x = np.arange(len(weights_selected.index))
bar_width = 0.27

plt.bar(
    x - bar_width,
    weights_selected["Constrained Mean-Variance"] * 100,
    width=bar_width,
    label="Constrained Mean-Variance"
)

plt.bar(
    x,
    weights_selected["CVaR Optimization"] * 100,
    width=bar_width,
    label="CVaR Optimization"
)

plt.bar(
    x + bar_width,
    weights_selected["Robust Mean-Variance"] * 100,
    width=bar_width,
    label="Robust Mean-Variance"
)

plt.xticks(x, weights_selected.index, rotation=75, ha="right")
plt.ylabel("Portfolio weight (%)")
plt.xlabel("Industry portfolio")
plt.title(
    f"Portfolio Weights Across the 49 Industry Portfolios "
    f"({selected_date.strftime('%B %Y')})"
)
plt.legend()
plt.grid(axis="y", alpha=0.3)
plt.tight_layout()

fig1_path = OUTPUT_DIR / "figure_portfolio_weights_selected_month.png"
plt.savefig(fig1_path, dpi=300)
plt.show()

print(f"Saved Figure 1: {fig1_path}")


# =====================================================
# FIGURE 2: WEIGHTS BY VOLATILITY QUINTILE
# =====================================================

estimation_data = returns.loc[returns.index < selected_date].tail(ROLLING_WINDOW)

if len(estimation_data) < ROLLING_WINDOW:
    raise ValueError("Not enough return observations before selected date.")

if estimation_data.isna().any().any():
    raise ValueError("Missing values in the volatility estimation window.")

volatility = estimation_data.std(ddof=1)

common_assets = weights_selected.index.intersection(volatility.index)

volatility = volatility.loc[common_assets]
weights_for_groups = weights_selected.loc[common_assets]

volatility_groups = pd.qcut(
    volatility.rank(method="first"),
    q=5,
    labels=[
        "Q1 lowest volatility",
        "Q2",
        "Q3",
        "Q4",
        "Q5 highest volatility"
    ]
)

grouped_weights = pd.DataFrame(index=volatility_groups.cat.categories)

for method in weights_for_groups.columns:
    grouped_weights[method] = (
        weights_for_groups[method]
        .groupby(volatility_groups, observed=False)
        .sum()
        * 100
    )


plt.figure(figsize=(11, 6))

x = np.arange(len(grouped_weights.index))
bar_width = 0.27

plt.bar(
    x - bar_width,
    grouped_weights["Constrained Mean-Variance"],
    width=bar_width,
    label="Constrained Mean-Variance"
)

plt.bar(
    x,
    grouped_weights["CVaR Optimization"],
    width=bar_width,
    label="CVaR Optimization"
)

plt.bar(
    x + bar_width,
    grouped_weights["Robust Mean-Variance"],
    width=bar_width,
    label="Robust Mean-Variance"
)

plt.xticks(x, grouped_weights.index, rotation=20, ha="right")
plt.ylabel("Total portfolio weight (%)")
plt.xlabel("Volatility quintile")
plt.title(
    f"Portfolio Weights by 60-Month Volatility Quintile "
    f"({selected_date.strftime('%B %Y')})"
)
plt.legend()
plt.grid(axis="y", alpha=0.3)
plt.tight_layout()

fig2_path = OUTPUT_DIR / "figure_weights_by_volatility_quintile.png"
plt.savefig(fig2_path, dpi=300)
plt.show()

print(f"Saved Figure 2: {fig2_path}")


# =====================================================
# OPTIONAL: PRINT GROUPED WEIGHTS TABLE
# =====================================================

print("\nWeights by volatility quintile:")
print(grouped_weights.round(2))

print("\nSelected-date portfolio weights:")
print((weights_selected * 100).round(2))